services:
  strapi:
    image: node:18-alpine
    container_name: strapi-working
    restart: unless-stopped
    volumes:
      - ./strapi-data:/opt/app
    ports:
      - '1337:1337'
    working_dir: /opt/app
    environment:
      NODE_ENV: development
    command: >
      sh -c "
        if [ ! -f package.json ]; then
          npx create-strapi-app@latest . --quickstart --no-run --skip-cloud
        fi &&
        npm run develop
      "